// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '..',
    appId: '..',
    messagingSenderId: '.',
    projectId: '.',
    authDomain: '.',
    storageBucket: '.',
    measurementId: '.',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '..',
    appId: '.',
    messagingSenderId: '.',
    projectId: '.',
    storageBucket: '.',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '.',
    appId: '1:593683635467:ios:994b2cee617d2b5f72560e',
    messagingSenderId: '593683635467',
    projectId: 'h4eelquiic',
    storageBucket: 'h4eelquiic.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVMuERrueTSJP5W3qvVkQS4V7j2WUfpb8',
    appId: '1:593683635467:ios:994b2cee617d2b5f72560e',
    messagingSenderId: '593683635467',
    projectId: 'h4eelquiic',
    storageBucket: 'h4eelquiic.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '..',
    appId: '..',
    messagingSenderId: '.',
    projectId: '.',
    authDomain: '.',
    storageBucket: '.',
    measurementId: '.',
  );
}
